/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Bg: typeof import('./src/components/container/bg.vue')['default']
    Dropdown: typeof import('./src/components/container/Dropdown.vue')['default']
    Dropdown_irr: typeof import('./src/components/container/Dropdown_irr.vue')['default']
    MultiSelectArray: typeof import('./src/components/container/MultiSelectArray.vue')['default']
    MultiSelectArray_irr: typeof import('./src/components/container/MultiSelectArray_irr.vue')['default']
    NumberSelecte: typeof import('./src/components/container/NumberSelecte.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
